title: Jens Knipper
description: Developer blog of Jens Knipper. Covering stories about software development, DevOps and Indie Hacking.

url: "https://jensknipper.de"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
logo: /icons/icon.png

markdown: kramdown
highlighter: rouge
paginate: 5

netlifycms: true

analytics: true

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Talks
    url: /talks
  - title: Contact
    url: /contact

social:
  github: JensKnipper

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - README.md
  - LICENSE
  - netlify.toml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
